var ErrorCode = (function () {
  var errorText = {
    1000: "A network request was made using an unsupported URI scheme",
    1001: [
      "Bad Http status -",
      "1.The resource cannot be found",
      "2.An error occurred while processing your request.",
    ],
    1002: "A network request failed with an error while fetching content",
    1003: "A network request timed out",
    1004: "A network request was made with a malformed data URI",
    1006: "A request filter threw an error",
    1007: "A response filter threw an error",
    1008: "A testing network request was made with a malformed URI",
    1009: "An unexpected network request was made to the FakeNetworkingEngine",
    1010: "The number of retry attempts have run out",
    2000: "The text parser failed to parse a text stream due to an invalid header.",
    2001: "The text parser failed to parse a text stream due to an invalid cue",
    2003: "Was unable to detect the encoding of the response text",
    2004: " The response data contains invalid Unicode character encoding",
    3008: "The WebM header parser was unable to locate the Ebml element",
    3014: "A MediaSource operation failed",
    3015: "A MediaSource operation threw an exception",
    3016: "The video element reported an error",
    3017: "A MediaSource operation threw QuotaExceededError and recovery failed.",
    4000: "The Player was unable to guess the manifest type based on file extension",
    4001: "The DASH Manifest contained invalid XML markup",
    4002: "The DASH Manifest contained a Representation with insufficient segment",
    4003: "The DASH Manifest contained an AdaptationSet with no Representations",
    4004: "The DASH Manifest contained an Period with no AdaptationSets.",
    4005: "The DASH Manifest does not specify an init segment with a WebM container.",
    4006: "The DASH Manifest contained an unsupported container format",
    4007: "The embedded PSSH data has invalid encoding",
    4015: "HLS playlist doesn't start with a mandory #EXTM3U tag",
    4016: "HLS tag has an invalid name",
    4017: "HLS playlist has both Master and Media/Segment tags",
    4022: "HLS-No Master Playlist has been provided.",
    4023: "HLS-One of the required attributes was not provided,",
    4024: "HLS-One of the required tags was not provided",
    4025: "The HLS parser was unable to guess codecs of a stream.",
    4030: "The HLS parser was unable to parse segment start time from the media",
    4032: "The content container or codecs are not supported by this browser",
    4033: "External text tracks cannot be added to live streams.",
    4034: "We do not support AES-128 encryption with HLS yet.",
    4035: "An internal error code that should never be seen by applications",
    6004: "The CDM rejected the server certificate supplied by the application.",
    6005: "The CDM refused to create a session for some unknown reason",
    6006: "The CDM was unable to generate a license request for the init data it was given.",
    6007: "The license request failed",
    6008: "The license response was rejected by the CDM.",
    6010: "The manifest does not specify any DRM info, but the content is encrypted.",
    6012: "A license server URI is required for every key system.",
    6013: "A required offline session was removed.",
    6014: "The license has expired",
    6015: "A server certificate wasn't given when it is required",
    6016: "An error was thrown while executing the init data transformation",
    6017: "The server certificate request failed.",
    7000: "The call to Player.load() was interrupted by a call to Player.unload()",
    7001: "An internal error which indicates that an operation was aborted",
    7002: "The call to Player.load() failed because the Player does not have a video element",
    7003: "The operation failed because the object has been destroyed",
    7004: "The content has not been loaded in the Player",
    9000: "Offline storage is not supported on this browser",
    9003: "The specified item was not found",
    9004: "A network request was made with a malformed offline URI",
    9005: "The specified content is live or in-progress",
  };

  return {
    errorText,
  };
})();
